### ISSUE TITLE
Approach with Listener

### ISSUE THREAD

**Issue by Shura1oplot** [spywhere/SelectExact#2]
I suggest use Listener approach to solve the issue.

``` python
# [SublimeLinter @python:3]

import sublime
import sublime_plugin


class FindUnderListener(sublime_plugin.EventListener):

    def on_window_command(self, window, command_name, args=None):  # (self (selfie
        if command_name not in ("find_under_expand", "find_all_under"):
            return

        if args and args.get("original_behaviour", False):
            return

        view = window.active_view()
        selection = view.sel()

        if len(selection) != 1:
            return

        region = selection[0]

        if region.empty():
            return

        text = view.substr(region)

        if not all(x.isalnum() or x == "_" for x in text):
            return

        if not view.classify(region.begin()) & sublime.CLASS_WORD_START:
            return

        if not view.classify(region.end()) & sublime.CLASS_WORD_END:
            return

        selection.clear()
        selection.add(sublime.Region(region.end(), region.end()))

        if command_name == "find_under_expand":
            window.run_command("find_under_expand")
```

The only thing affected by this code is when you select 1 word and press ctrl+d or alt+f3. In that case selection is resetted and `find_under_expand` command is doubled (first execution - to select word under cursor, second one - to select next word).

Your version does not scroll view if next word to select is out of the screen. Also, command `find_under_expand` starts selecting words from the beginning of the file if the end is reached.

**Comment by spywhere** [comment]
Thanks for the suggestion. Your approach seems nice but I guess (aka. I did not test it) it would override the `find_under_expand` and `find_all_under` command behaviour. Surely, my approach did not scroll the view when the selection is out of the screen but, selecting words from the beginning of the file if the end is reached is already implemented.

I will mark this as an enhancement for the scrolling view when selection is out of the screen though.

**Comment by Shura1oplot** [comment]
@spywhere, you can change behaviour by adding an optional argument to the commands. I updated code in the first comment to show it. Config to use original commands behaviour:

```
{"keys": ["ctrl+alt+d"], "command": "find_under_expand", "args":{"original_behaviour": true}},
```

**Comment by spywhere** [comment]
The scrolling is now implemented in v0.1.1. However, the suggestion on plugin implementation still the same. I will close this issue for the scrolling behaviour but the implementation suggestion might be considered later.
